version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - .:/var/lib/postgresql/data
